# Generated by Django 3.2.4 on 2021-06-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cotent',
            new_name='content',
        ),
    ]
